[project]
name = "ics-to-gcal"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Silma Thoron", email = "paulgivel@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client==2.149.0",
    "google-auth==2.35.0",
    "google-auth-oauthlib==1.2.1",
    "icalendar==6.1.0",
]

[project.scripts]
ics-to-gcal = "import_ics:main"
build = "build:main"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["build", "import_ics"]
